
DROP TABLE IF EXISTS ProductAmounts
create table ProductAmounts
(
    Id               int identity
        constraint PK_ProductAmounts
            primary key,
    CreationDate     datetime2 not null,
    ModificationDate datetime2 not null,
    IsDeleted        bit       not null,
    CategoryUrl      nvarchar(max),
    Amount           real      not null,
    IsActive         bit       not null,go
    [Order]          int       not null
)
go

INSERT INTO dbo.ProductAmounts VALUES 
(GETDATE(), GETDATE(), 0, 'grado', 1450, 1, 1),
(GETDATE(), GETDATE(), 0, 'master-universitario', 3900, 1, 1),
(GETDATE(), GETDATE(), 0, 'master', 3900, 1, 1),
(GETDATE(), GETDATE(), 0, 'experto', 1750, 1, 1),
(GETDATE(), GETDATE(), 0, 'curso', 65, 1, 1),
(GETDATE(), GETDATE(), 0, 'oposiciones', 790, 1, 1),
(GETDATE(), GETDATE(), 0, 'Clases en directo', 940, 1, 1),
(GETDATE(), GETDATE(), 0, 'curso-idiomas', 390, 1, 1),
(GETDATE(), GETDATE(), 0, 'curso-idiomas', 490, 1, 1),
(GETDATE(), GETDATE(), 0, 'Examen Oficial', 210, 1, 1),
(GETDATE(), GETDATE(), 0, 'Evaluación Oficial', 210, 1, 1),
(GETDATE(), GETDATE(), 0, 'CFC', 99, 1, 1);

---

DROP TABLE IF EXISTS ProductCountryFacultyModifiers
create table ProductCountryFacultyModifiers
(
    Id               int identity
        constraint PK_ProductCountryFacultyModifiers
            primary key,
    CreationDate     datetime2 not null,
    ModificationDate datetime2 not null,
    IsDeleted        bit       not null,
    CountryCode      nvarchar(max),
    CategoryUrl      nvarchar(max),
    Value            real      not null,
    IsActive         bit       not null,
    [Order]          int       not null
)
go

INSERT INTO dbo.ProductCountryFacultyModifiers VALUES 
(GETDATE(), GETDATE(), 0, 'ES', 'escuela-de-negocios', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'ES', 'medicina', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'ES', 'odontologia', 1.25, 1, 1),
(GETDATE(), GETDATE(), 0, 'ES', 'farmacia', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'ES', 'enfermeria', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'ES', 'fisioterapia', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'ES', 'nutricion', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'ES', 'psicologia', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'ES', 'educacion', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'ES', 'filosofia', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'ES', 'escuela-de-idiomas', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'AR', 'escuela-de-negocios', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'AR', 'medicina', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'AR', 'odontologia', 1.25, 1, 1),
(GETDATE(), GETDATE(), 0, 'AR', 'farmacia', 0.5, 1, 1),
(GETDATE(), GETDATE(), 0, 'AR', 'enfermeria', 0.5, 1, 1),
(GETDATE(), GETDATE(), 0, 'AR', 'fisioterapia', 0.5, 1, 1),
(GETDATE(), GETDATE(), 0, 'AR', 'nutricion', 0.6, 1, 1),
(GETDATE(), GETDATE(), 0, 'AR', 'psicologia', 0.6, 1, 1),
(GETDATE(), GETDATE(), 0, 'AR', 'educacion', 0.5, 1, 1),
(GETDATE(), GETDATE(), 0, 'AR', 'filosofia', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'AR', 'escuela-de-idiomas', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'CO', 'escuela-de-negocios', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'CO', 'medicina', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'CO', 'odontologia', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'CO', 'farmacia', 0.5, 1, 1),
(GETDATE(), GETDATE(), 0, 'CO', 'enfermeria', 0.5, 1, 1),
(GETDATE(), GETDATE(), 0, 'CO', 'fisioterapia', 0.5, 1, 1),
(GETDATE(), GETDATE(), 0, 'CO', 'nutricion', 0.6, 1, 1),
(GETDATE(), GETDATE(), 0, 'CO', 'psicologia', 0.6, 1, 1),
(GETDATE(), GETDATE(), 0, 'CO', 'educacion', 0.5, 1, 1),
(GETDATE(), GETDATE(), 0, 'CO', 'filosofia', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'CO', 'escuela-de-idiomas', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'MX', 'escuela-de-negocios', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'MX', 'medicina', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'MX', 'odontologia', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'MX', 'farmacia', 0.5, 1, 1),
(GETDATE(), GETDATE(), 0, 'MX', 'enfermeria', 0.5, 1, 1),
(GETDATE(), GETDATE(), 0, 'MX', 'fisioterapia', 0.5, 1, 1),
(GETDATE(), GETDATE(), 0, 'MX', 'nutricion', 0.6, 1, 1),
(GETDATE(), GETDATE(), 0, 'MX', 'psicologia', 0.6, 1, 1),
(GETDATE(), GETDATE(), 0, 'MX', 'educacion', 0.5, 1, 1),
(GETDATE(), GETDATE(), 0, 'MX', 'filosofia', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'MX', 'escuela-de-idiomas', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'PE', 'escuela-de-negocios', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'PE', 'medicina', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'PE', 'odontologia', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'PE', 'farmacia', 0.5, 1, 1),
(GETDATE(), GETDATE(), 0, 'PE', 'enfermeria', 0.5, 1, 1),
(GETDATE(), GETDATE(), 0, 'PE', 'fisioterapia', 0.5, 1, 1),
(GETDATE(), GETDATE(), 0, 'PE', 'nutricion', 0.6, 1, 1),
(GETDATE(), GETDATE(), 0, 'PE', 'psicologia', 0.6, 1, 1),
(GETDATE(), GETDATE(), 0, 'PE', 'educacion', 0.5, 1, 1),
(GETDATE(), GETDATE(), 0, 'PE', 'filosofia', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'PE', 'escuela-de-idiomas', 1, 1, 1);

--
DROP TABLE IF EXISTS ProductCountryModifiers
create table ProductCountryModifiers
(
    Id               int identity
        constraint PK_ProductCountryModifiers
            primary key,
    CreationDate     datetime2 not null,
    ModificationDate datetime2 not null,
    IsDeleted        bit       not null,
    CountryCode      nvarchar(max),
    CategoryUrl      nvarchar(max),
    Value            real      not null,
    IsActive         bit       not null,
    [Order]          int       not null
)
go

INSERT INTO dbo.ProductCountryModifiers VALUES 
(GETDATE(), GETDATE(), 0, 'ES', 'grado', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'ES', 'master-universitario', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'ES', 'master', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'ES', 'experto-universitario', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'ES', 'curso-universitario', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'ES', 'ope-enfermeria', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'ES', 'clases-conversacion-online', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'ES', 'curso-universitario a1-b2', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'ES', 'curso-universitario c1 - c2', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'ES', 'examenes-oficiales', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'ES', 'evaluacion-oficial', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'ES', 'cfc', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'AR', 'licenciatura', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'AR', 'maestria-oficial', 0.56, 1, 1),
(GETDATE(), GETDATE(), 0, 'AR', 'maestria', 0.56, 1, 1),
(GETDATE(), GETDATE(), 0, 'AR', 'especializacion', 0.56, 1, 1),
(GETDATE(), GETDATE(), 0, 'AR', 'diplomado', 1.23, 1, 1),
(GETDATE(), GETDATE(), 0, 'AR', 'clases-conversacion-online', 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'AR', 'curso a1-b2', 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'AR', 'curso c1-c2', 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'AR', 'examenes-oficiales', 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'AR', 'evaluacion-oficial', 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'CO', 'licenciatura', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'CO', 'maestria-oficial', 0.98, 1, 1),
(GETDATE(), GETDATE(), 0, 'CO', 'maestria', 0.98, 1, 1),
(GETDATE(), GETDATE(), 0, 'CO', 'especializacion', 0.91, 1, 1),
(GETDATE(), GETDATE(), 0, 'CO', 'diplomado', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'CO', 'clases-conversacion-online', 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'CO', 'curso  a1-b2', 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'CO', 'curso  c1-c2', 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'CO', 'examenes-oficiales', 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'CO', 'evaluacion-oficial', 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'MX', 'licenciatura', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'MX', 'maestria-rvoe', 1.17, 1, 1),
(GETDATE(), GETDATE(), 0, 'MX', 'maestria', 1.17, 1, 1),
(GETDATE(), GETDATE(), 0, 'MX', 'especializacion', 1.16, 1, 1),
(GETDATE(), GETDATE(), 0, 'MX', 'diplomado', 2.43, 1, 1),
(GETDATE(), GETDATE(), 0, 'MX', 'clases-conversacion-online', 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'MX', 'curso a1-b2', 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'MX', 'curso c1-c2', 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'MX', 'examenes-oficiales', 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'MX', 'evaluacion-oficial', 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'PE', 'licenciatura', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'PE', 'maestria-oficial', 1.03, 1, 1),
(GETDATE(), GETDATE(), 0, 'PE', 'maestria', 1.03, 1, 1),
(GETDATE(), GETDATE(), 0, 'PE', 'especializacion', 0.97, 1, 1),
(GETDATE(), GETDATE(), 0, 'PE', 'diplomado', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'PE', 'clases-conversacion-online', 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'PE', 'curso a1-b2', 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'PE', 'curso c1-c2', 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'PE', 'examenes-oficiales', 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'PE', 'evaluacion-oficial', 0, 1, 1);

---
DROP TABLE IF EXISTS ProductFacultyStudyModifiers
create table ProductFacultyStudyModifiers
(
    Id               int identity
        constraint PK_ProductFacultyStudyModifiers
            primary key,
    CreationDate     datetime2 not null,
    ModificationDate datetime2 not null,
    IsDeleted        bit       not null,
    FacultyUrl       nvarchar(max),
    CategoryUrl      nvarchar(max),
    Value            real      not null,
    IsActive         bit       not null,
    [Order]          int       not null
)
go

INSERT INTO dbo.ProductFacultyStudyModifiers VALUES 
(GETDATE(), GETDATE(), 0, 'escuela-de-negocios', 'grado', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'escuela-de-negocios', 'master-universitario', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'escuela-de-negocios', 'master', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'escuela-de-negocios', 'experto', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'escuela-de-negocios', 'curso', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'escuela-de-negocios', 'oposiciones', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'escuela-de-negocios', 'Clases en directo', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'escuela-de-negocios', 'curso-idiomas', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'escuela-de-negocios', 'curso-idiomas', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'escuela-de-negocios', 'Examen Oficial', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'escuela-de-negocios', 'Evaluación Oficial', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'escuela-de-negocios', 'CFC', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'medicina', 'grado', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'medicina', 'master-universitario', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'medicina', 'master', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'medicina', 'experto', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'medicina', 'curso', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'medicina', 'oposiciones', 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'medicina', 'Clases en directo', 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'medicina', 'curso-idiomas A1 - B2', 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'medicina', 'curso-idiomas C1 - C2', 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'medicina', 'Examen Oficial', 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'medicina', 'Evaluación Oficial', 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'medicina', 'CFC', 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'odontologia', 'grado', 1.25, 1, 1),
(GETDATE(), GETDATE(), 0, 'odontologia', 'master-universitario', 1.25, 1, 1),
(GETDATE(), GETDATE(), 0, 'odontologia', 'master', 1.25, 1, 1),
(GETDATE(), GETDATE(), 0, 'odontologia', 'experto', 1.25, 1, 1),
(GETDATE(), GETDATE(), 0, 'odontologia', 'curso', 1.25, 1, 1),
(GETDATE(), GETDATE(), 0, 'odontologia', 'oposiciones', 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'odontologia', 'Clases en directo', 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'odontologia', 'curso-idiomas A1 - B2', 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'odontologia', 'curso-idiomas C1 - C2', 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'odontologia', 'Examen Oficial', 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'odontologia', 'Evaluación Oficial', 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'odontologia', 'CFC', 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'farmacia', 'grado', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'farmacia', 'master-universitario', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'farmacia', 'master', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'farmacia', 'experto', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'farmacia', 'curso', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'farmacia', 'oposiciones', 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'farmacia', 'Clases en directo', 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'farmacia', 'curso-idiomas A1 - B2', 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'farmacia', 'curso-idiomas C1 - C2', 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'farmacia', 'Examen Oficial', 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'farmacia', 'Evaluación Oficial', 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'farmacia', 'CFC', 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'enfermeria', 'grado', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'enfermeria', 'master-universitario', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'enfermeria', 'master', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'enfermeria', 'experto', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'enfermeria', 'curso', 0.8, 1, 1),
(GETDATE(), GETDATE(), 0, 'enfermeria', 'oposiciones', 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'enfermeria', 'Clases en directo', 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'enfermeria', 'curso-idiomas A1 - B2', 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'enfermeria', 'curso-idiomas C1 - C2', 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'enfermeria', 'Examen Oficial', 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'enfermeria', 'Evaluación Oficial', 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'enfermeria', 'CFC', 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'fisioterapia', 'grado', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'fisioterapia', 'master-universitario', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'fisioterapia', 'master', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'fisioterapia', 'experto', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'fisioterapia', 'curso', 0.7, 1, 1),
(GETDATE(), GETDATE(), 0, 'fisioterapia', 'oposiciones', 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'fisioterapia', 'Clases en directo', 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'fisioterapia', 'curso-idiomas A1 - B2', 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'fisioterapia', 'curso-idiomas C1 - C2', 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'fisioterapia', 'Examen Oficial', 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'fisioterapia', 'Evaluación Oficial', 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'fisioterapia', 'CFC', 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'nutricion', 'grado', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'nutricion', 'master-universitario', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'nutricion', 'master', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'nutricion', 'experto', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'nutricion', 'curso', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'nutricion', 'oposiciones', 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'nutricion', 'Clases en directo', 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'nutricion', 'curso-idiomas A1 - B2', 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'nutricion', 'curso-idiomas C1 - C2', 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'nutricion', 'Examen Oficial', 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'nutricion', 'Evaluación Oficial', 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'nutricion', 'CFC', 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'psicologia', 'grado', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'psicologia', 'master-universitario', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'psicologia', 'master', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'psicologia', 'experto', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'psicologia', 'curso', 0.7, 1, 1),
(GETDATE(), GETDATE(), 0, 'psicologia', 'oposiciones', 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'psicologia', 'Clases en directo', 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'psicologia', 'curso-idiomas A1 - B2', 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'psicologia', 'curso-idiomas C1 - C2', 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'psicologia', 'Examen Oficial', 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'psicologia', 'Evaluación Oficial', 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'psicologia', 'CFC', 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'educacion', 'grado', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'educacion', 'master-universitario', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'educacion', 'master', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'educacion', 'experto', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'educacion', 'curso', 0.6, 1, 1),
(GETDATE(), GETDATE(), 0, 'educacion', 'oposiciones', 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'educacion', 'Clases en directo', 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'educacion', 'curso-idiomas A1 - B2', 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'educacion', 'curso-idiomas C1 - C2', 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'educacion', 'Examen Oficial', 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'educacion', 'Evaluación Oficial', 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'educacion', 'CFC', 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'filosofia', 'grado', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'filosofia', 'master-universitario', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'filosofia', 'master', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'filosofia', 'experto', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'filosofia', 'curso', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'filosofia', 'oposiciones', 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'filosofia', 'Clases en directo', 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'filosofia', 'curso-idiomas A1 - B2', 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'filosofia', 'curso-idiomas C1 - C2', 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'filosofia', 'Examen Oficial', 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'filosofia', 'Evaluación Oficial', 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'filosofia', 'CFC', 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'escuela-de-idiomas', 'grado', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'escuela-de-idiomas', 'master-universitario', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'escuela-de-idiomas', 'master', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'escuela-de-idiomas', 'experto', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'escuela-de-idiomas', 'curso', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'escuela-de-idiomas', 'oposiciones', 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'escuela-de-idiomas', 'Clases en directo', 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'escuela-de-idiomas', 'curso-idiomas A1 - B2', 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'escuela-de-idiomas', 'curso-idiomas C1 - C2', 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'escuela-de-idiomas', 'Examen Oficial', 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'escuela-de-idiomas', 'Evaluación Oficial', 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'escuela-de-idiomas', 'CFC', 0, 1, 1);


----
DROP TABLE IF EXISTS ProductCouponDiscountCountryModifiers
create table ProductCouponDiscountCountryModifiers
(
    Id               int identity
        constraint PK_ProductCouponDiscountCountryModifiers
            primary key,
    CreationDate     datetime2 not null,
    ModificationDate datetime2 not null,
    IsDeleted        bit       not null,
    CountryCode      nvarchar(max),
    CategoryUrl      nvarchar(max),
    Value            real      not null,
    IsActive         bit       not null,
    [Order]          int       not null
)
go

INSERT INTO dbo.ProductCouponDiscountCountryModifiers VALUES 
(GETDATE(), GETDATE(), 0, 'ES', 'grado', 0.862, 1, 1),
(GETDATE(), GETDATE(), 0, 'ES', 'master-universitario', 0.7564, 1, 1),
(GETDATE(), GETDATE(), 0, 'ES', 'master', 0.7564, 1, 1),
(GETDATE(), GETDATE(), 0, 'ES', 'experto-universitario', 0.7142, 1, 1),
(GETDATE(), GETDATE(), 0, 'ES', 'curso-universitario', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'ES', 'ope-enfermeria', 0.81, 1, 1),
(GETDATE(), GETDATE(), 0, 'ES', 'clases-conversacion-online', 0.8936, 1, 1),
(GETDATE(), GETDATE(), 0, 'ES', 'curso-universitario a1-b2', 0.7435, 1, 1),
(GETDATE(), GETDATE(), 0, 'ES', 'curso-universitario c1 - c2', 0.7959, 1, 1),
(GETDATE(), GETDATE(), 0, 'ES', 'examenes-oficiales', 0.5238, 1, 1),
(GETDATE(), GETDATE(), 0, 'ES', 'evaluacion-oficial', 0.5238, 1, 1),
(GETDATE(), GETDATE(), 0, 'ES', 'cfc', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'AR', 'licenciatura', 0.862, 1, 1),
(GETDATE(), GETDATE(), 0, 'AR', 'maestria-oficial', 0.7104, 1, 1),
(GETDATE(), GETDATE(), 0, 'AR', 'maestria', 0.7104, 1, 1),
(GETDATE(), GETDATE(), 0, 'AR', 'especializacion', 0.7143, 1, 1),
(GETDATE(), GETDATE(), 0, 'AR', 'diplomado', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'AR', 'ope-enfermeria', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'AR', 'clases-conversacion-online', 0.862, 1, 1),
(GETDATE(), GETDATE(), 0, 'AR', 'curso a1-b2', 0.8936, 1, 1),
(GETDATE(), GETDATE(), 0, 'AR', 'curso c1 - c2', 0.7435, 1, 1),
(GETDATE(), GETDATE(), 0, 'AR', 'examenes-oficiales', 0.7959, 1, 1),
(GETDATE(), GETDATE(), 0, 'AR', 'evaluacion-oficial', 0.5238, 1, 1),
(GETDATE(), GETDATE(), 0, 'AR', 'cfc', 0.5238, 1, 1),
(GETDATE(), GETDATE(), 0, 'CO', 'licenciatura', 0.8643, 1, 1),
(GETDATE(), GETDATE(), 0, 'CO', 'maestria-oficial', 0.7368, 1, 1),
(GETDATE(), GETDATE(), 0, 'CO', 'maestria', 0.7368, 1, 1),
(GETDATE(), GETDATE(), 0, 'CO', 'especializacion', 0.5833, 1, 1),
(GETDATE(), GETDATE(), 0, 'CO', 'diplomado', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'CO', 'ope-enfermeria', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'CO', 'clases-conversacion-online', 0.8906, 1, 1),
(GETDATE(), GETDATE(), 0, 'CO', 'curso  a1-b2', 0.7404, 1, 1),
(GETDATE(), GETDATE(), 0, 'CO', 'curso  c1 - c2', 0.7941, 1, 1),
(GETDATE(), GETDATE(), 0, 'CO', 'examenes-oficiales', 0.7941, 1, 1),
(GETDATE(), GETDATE(), 0, 'CO', 'evaluacion-oficial', 0.4927, 1, 1),
(GETDATE(), GETDATE(), 0, 'CO', 'cfc', 0.4927, 1, 1),
(GETDATE(), GETDATE(), 0, 'MX', 'licenciatura', 0.8621, 1, 1),
(GETDATE(), GETDATE(), 0, 'MX', 'maestria-rvoe', 0.7, 1, 1),
(GETDATE(), GETDATE(), 0, 'MX', 'maestria', 0.7, 1, 1),
(GETDATE(), GETDATE(), 0, 'MX', 'especializacion', 0.7, 1, 1),
(GETDATE(), GETDATE(), 0, 'MX', 'diplomado', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'MX', 'ope-enfermeria', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'MX', 'clases-conversacion-online', 0.8621, 1, 1),
(GETDATE(), GETDATE(), 0, 'MX', 'curso a1-b2', 0.8999, 1, 1),
(GETDATE(), GETDATE(), 0, 'MX', 'curso c1 - c2', 0.7775, 1, 1),
(GETDATE(), GETDATE(), 0, 'MX', 'examenes-oficiales', 0.823, 1, 1),
(GETDATE(), GETDATE(), 0, 'MX', 'evaluacion-oficial', 0.9109, 1, 1),
(GETDATE(), GETDATE(), 0, 'MX', 'cfc', 0.9109, 1, 1),
(GETDATE(), GETDATE(), 0, 'PE', 'licenciatura', 0.8637, 1, 1),
(GETDATE(), GETDATE(), 0, 'PE', 'maestria-oficial', 0.9, 1, 1),
(GETDATE(), GETDATE(), 0, 'PE', 'maestria', 0.9, 1, 1),
(GETDATE(), GETDATE(), 0, 'PE', 'especializacion', 0.8986, 1, 1),
(GETDATE(), GETDATE(), 0, 'PE', 'diplomado', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'PE', 'ope-enfermeria', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'PE', 'clases-conversacion-online', 0.8637, 1, 1),
(GETDATE(), GETDATE(), 0, 'PE', 'curso a1-b2', 0.8892, 1, 1),
(GETDATE(), GETDATE(), 0, 'PE', 'curso c1-c2', 0.7466, 1, 1),
(GETDATE(), GETDATE(), 0, 'PE', 'examenes-oficiales', 0.7989, 1, 1),
(GETDATE(), GETDATE(), 0, 'PE', 'evaluacion-oficial', 0.4933, 1, 1),
(GETDATE(), GETDATE(), 0, 'PE', 'cfc', 0.4933, 1, 1);

---
DROP TABLE IF EXISTS ProductCouponDiscountFacultyStudyModifiers
create table ProductCouponDiscountFacultyStudyModifiers
(
    Id               int identity
        constraint PK_ProductCouponDiscountFacultyStudyModifiers
            primary key,
    CreationDate     datetime2 not null,
    ModificationDate datetime2 not null,
    IsDeleted        bit       not null,
    FacultyUrl       nvarchar(max),
    CategoryUrl      nvarchar(max),
    Value            real      not null,
    IsActive         bit       not null,
    [Order]          int       not null
)
go

INSERT INTO dbo.ProductCouponDiscountFacultyStudyModifiers VALUES 
(GETDATE(), GETDATE(), 0, 'escuela-de-negocios', 'grado', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'escuela-de-negocios', 'master-universitario', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'escuela-de-negocios', 'master', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'escuela-de-negocios', 'experto', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'escuela-de-negocios', 'curso', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'escuela-de-negocios', 'oposiciones', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'escuela-de-negocios', 'Clases en directo', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'escuela-de-negocios', 'curso-idiomas', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'escuela-de-negocios', 'curso-idiomas', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'escuela-de-negocios', 'Examen Oficial', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'escuela-de-negocios', 'Evaluación Oficial', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'escuela-de-negocios', 'CFC', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'medicina', 'grado', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'medicina', 'master-universitario', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'medicina', 'master', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'medicina', 'experto', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'medicina', 'curso', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'medicina', 'oposiciones', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'medicina', 'Clases en directo', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'medicina', 'curso-idiomas', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'medicina', 'curso-idiomas', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'medicina', 'Examen Oficial', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'medicina', 'Evaluación Oficial', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'medicina', 'CFC', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'odontologia', 'grado', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'odontologia', 'master-universitario', 1.0657, 1, 1),
(GETDATE(), GETDATE(), 0, 'odontologia', 'master', 1.0657, 1, 1),
(GETDATE(), GETDATE(), 0, 'odontologia', 'experto', 1.1455, 1, 1),
(GETDATE(), GETDATE(), 0, 'odontologia', 'curso', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'odontologia', 'oposiciones', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'odontologia', 'Clases en directo', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'odontologia', 'curso-idiomas', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'odontologia', 'curso-idiomas', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'Ecuador', 'Examen Oficial', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'odontologia', 'Evaluación Oficial', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'odontologia', 'CFC', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'farmacia', 'grado', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'farmacia', 'master-universitario', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'farmacia', 'master', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'farmacia', 'experto', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'farmacia', 'curso', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'farmacia', 'oposiciones', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'farmacia', 'Clases en directo', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'farmacia', 'curso-idiomas', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'farmacia', 'curso-idiomas', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'farmacia', 'Examen Oficial', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'farmacia', 'Evaluación Oficial', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'farmacia', 'CFC', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'enfermeria', 'grado', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'enfermeria', 'master-universitario', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'enfermeria', 'master', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'enfermeria', 'experto', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'enfermeria', 'curso', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'enfermeria', 'oposiciones', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'enfermeria', 'Clases en directo', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'enfermeria', 'curso-idiomas', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'enfermeria', 'curso-idiomas', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'enfermeria', 'Examen Oficial', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'enfermeria', 'Evaluación Oficial', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'enfermeria', 'CFC', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'fisioterapia', 'grado', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'fisioterapia', 'master-universitario', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'fisioterapia', 'master', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'fisioterapia', 'experto', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'fisioterapia', 'curso', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'fisioterapia', 'oposiciones', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'fisioterapia', 'Clases en directo', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'fisioterapia', 'curso-idiomas', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'fisioterapia', 'curso-idiomas', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'fisioterapia', 'Examen Oficial', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'fisioterapia', 'Evaluación Oficial', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'fisioterapia', 'CFC', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'nutricion', 'grado', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'nutricion', 'master-universitario', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'nutricion', 'master', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'nutricion', 'experto', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'nutricion', 'curso', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'nutricion', 'oposiciones', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'nutricion', 'Clases en directo', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'nutricion', 'curso-idiomas', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'nutricion', 'curso-idiomas', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'nutricion', 'Examen Oficial', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'nutricion', 'Evaluación Oficial', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'nutricion', 'CFC', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'psicologia', 'grado', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'psicologia', 'master-universitario', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'psicologia', 'master', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'psicologia', 'experto', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'psicologia', 'curso', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'psicologia', 'oposiciones', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'psicologia', 'Clases en directo', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'psicologia', 'curso-idiomas', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'psicologia', 'curso-idiomas', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'psicologia', 'Examen Oficial', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'psicologia', 'Evaluación Oficial', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'psicologia', 'CFC', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'educacion', 'grado', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'educacion', 'master-universitario', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'educacion', 'master', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'educacion', 'experto', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'educacion', 'curso', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'educacion', 'oposiciones', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'educacion', 'Clases en directo', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'educacion', 'curso-idiomas', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'educacion', 'curso-idiomas', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'educacion', 'Examen Oficial', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'educacion', 'Evaluación Oficial', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'educacion', 'CFC', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'filosofia', 'grado', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'filosofia', 'master-universitario', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'filosofia', 'master', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'filosofia', 'experto', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'filosofia', 'curso', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'filosofia', 'oposiciones', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'filosofia', 'Clases en directo', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'filosofia', 'curso-idiomas', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'filosofia', 'curso-idiomas', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'filosofia', 'Examen Oficial', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'filosofia', 'Evaluación Oficial', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'filosofia', 'CFC', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'escuela-de-idiomas', 'grado', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'escuela-de-idiomas', 'master-universitario', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'escuela-de-idiomas', 'master', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'escuela-de-idiomas', 'experto', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'escuela-de-idiomas', 'curso', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'escuela-de-idiomas', 'oposiciones', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'escuela-de-idiomas', 'Clases en directo', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'escuela-de-idiomas', 'curso-idiomas', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'escuela-de-idiomas', 'curso-idiomas', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'escuela-de-idiomas', 'Examen Oficial', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'escuela-de-idiomas', 'Evaluación Oficial', 1, 1, 1),
(GETDATE(), GETDATE(), 0, 'escuela-de-idiomas', 'CFC', 1, 1, 1);

---
DROP TABLE IF EXISTS ProductScholarshipCountryModifiers
create table ProductScholarshipCountryModifiers
(
    Id               int identity
        constraint PK_ProductScholarshipCountryModifiers
            primary key,
    CreationDate     datetime2 not null,
    ModificationDate datetime2 not null,
    IsDeleted        bit       not null,
    CountryCode      nvarchar(max),
    CategoryUrl      nvarchar(max),
    Value            real      not null,
    IsActive         bit       not null,
    [Order]          int       not null
)
go

INSERT INTO dbo.ProductScholarshipCountryModifiers  VALUES
(GETDATE(), GETDATE(), 0, 'ES', 'grado', 0.5, 1, 1),
(GETDATE(), GETDATE(), 0, 'ES', 'master-universitario', 0.5, 1, 1),
(GETDATE(), GETDATE(), 0, 'ES', 'master', 0.5, 1, 1),
(GETDATE(), GETDATE(), 0, 'ES', 'experto-universitario', 0.5, 1, 1),
(GETDATE(), GETDATE(), 0, 'ES', 'curso-universitario', 0.5, 1, 1),
(GETDATE(), GETDATE(), 0, 'ES', 'ope-enfermeria', 0.5, 1, 1),
(GETDATE(), GETDATE(), 0, 'ES', 'clases-conversacion-online', 0.5, 1, 1),
(GETDATE(), GETDATE(), 0, 'ES', 'curso-universitario a1-b2', 0.5, 1, 1),
(GETDATE(), GETDATE(), 0, 'ES', 'curso-universitario a1-b2', 0.5, 1, 1),
(GETDATE(), GETDATE(), 0, 'ES', 'clases-conversacion-online', 0.5, 1, 1),
(GETDATE(), GETDATE(), 0, 'ES', 'curso-universitario a1-b2', 0.5, 1, 1),
(GETDATE(), GETDATE(), 0, 'ES', 'clases-conversacion-online', 0.5, 1, 1),
(GETDATE(), GETDATE(), 0, 'AR', 'grado', 0.5, 1, 1),
(GETDATE(), GETDATE(), 0, 'AR', 'master-universitario', 0.5, 1, 1),
(GETDATE(), GETDATE(), 0, 'AR', 'master', 0.5, 1, 1),
(GETDATE(), GETDATE(), 0, 'AR', 'experto-universitario', 0.5, 1, 1),
(GETDATE(), GETDATE(), 0, 'AR', 'curso-universitario', 0.5, 1, 1),
(GETDATE(), GETDATE(), 0, 'AR', 'ope-enfermeria', 0.5, 1, 1),
(GETDATE(), GETDATE(), 0, 'AR', 'clases-conversacion-online', 0.5, 1, 1),
(GETDATE(), GETDATE(), 0, 'AR', 'curso-universitario a1-b2', 0.5, 1, 1),
(GETDATE(), GETDATE(), 0, 'AR', 'curso-universitario a1-b2', 0.5, 1, 1),
(GETDATE(), GETDATE(), 0, 'AR', 'clases-conversacion-online', 0.5, 1, 1),
(GETDATE(), GETDATE(), 0, 'AR', 'curso-universitario a1-b2', 0.5, 1, 1),
(GETDATE(), GETDATE(), 0, 'AR', 'clases-conversacion-online', 0.5, 1, 1),
(GETDATE(), GETDATE(), 0, 'CO', 'grado', 0.5, 1, 1),
(GETDATE(), GETDATE(), 0, 'CO', 'master-universitario', 0.5, 1, 1),
(GETDATE(), GETDATE(), 0, 'CO', 'master', 0.5, 1, 1),
(GETDATE(), GETDATE(), 0, 'CO', 'experto-universitario', 0.5, 1, 1),
(GETDATE(), GETDATE(), 0, 'CO', 'curso-universitario', 0.5, 1, 1),
(GETDATE(), GETDATE(), 0, 'CO', 'ope-enfermeria', 0.5, 1, 1),
(GETDATE(), GETDATE(), 0, 'CO', 'clases-conversacion-online', 0.5, 1, 1),
(GETDATE(), GETDATE(), 0, 'CO', 'curso-universitario a1-b2', 0.5, 1, 1),
(GETDATE(), GETDATE(), 0, 'CO', 'curso-universitario a1-b2', 0.5, 1, 1),
(GETDATE(), GETDATE(), 0, 'CO', 'clases-conversacion-online', 0.5, 1, 1),
(GETDATE(), GETDATE(), 0, 'CO', 'curso-universitario a1-b2', 0.5, 1, 1),
(GETDATE(), GETDATE(), 0, 'CO', 'clases-conversacion-online', 0.5, 1, 1),
(GETDATE(), GETDATE(), 0, 'MX', 'grado', 0.5, 1, 1),
(GETDATE(), GETDATE(), 0, 'MX', 'master-universitario', 0.5, 1, 1),
(GETDATE(), GETDATE(), 0, 'MX', 'master', 0.5, 1, 1),
(GETDATE(), GETDATE(), 0, 'MX', 'experto-universitario', 0.5, 1, 1),
(GETDATE(), GETDATE(), 0, 'MX', 'curso-universitario', 0.5, 1, 1),
(GETDATE(), GETDATE(), 0, 'MX', 'ope-enfermeria', 0.5, 1, 1),
(GETDATE(), GETDATE(), 0, 'MX', 'clases-conversacion-online', 0.5, 1, 1),
(GETDATE(), GETDATE(), 0, 'MX', 'curso-universitario a1-b2', 0.5, 1, 1),
(GETDATE(), GETDATE(), 0, 'MX', 'curso-universitario a1-b2', 0.5, 1, 1),
(GETDATE(), GETDATE(), 0, 'MX', 'clases-conversacion-online', 0.5, 1, 1),
(GETDATE(), GETDATE(), 0, 'MX', 'curso-universitario a1-b2', 0.5, 1, 1),
(GETDATE(), GETDATE(), 0, 'MX', 'clases-conversacion-online', 0.5, 1, 1),
(GETDATE(), GETDATE(), 0, 'PE', 'grado', 0.5, 1, 1),
(GETDATE(), GETDATE(), 0, 'PE', 'master-universitario', 0.5, 1, 1),
(GETDATE(), GETDATE(), 0, 'PE', 'master', 0.5, 1, 1),
(GETDATE(), GETDATE(), 0, 'PE', 'experto-universitario', 0.5, 1, 1),
(GETDATE(), GETDATE(), 0, 'PE', 'curso-universitario', 0.5, 1, 1),
(GETDATE(), GETDATE(), 0, 'PE', 'ope-enfermeria', 0.5, 1, 1),
(GETDATE(), GETDATE(), 0, 'PE', 'clases-conversacion-online', 0.5, 1, 1),
(GETDATE(), GETDATE(), 0, 'PE', 'curso-universitario a1-b2', 0.5, 1, 1),
(GETDATE(), GETDATE(), 0, 'PE', 'curso-universitario a1-b2', 0.5, 1, 1),
(GETDATE(), GETDATE(), 0, 'PE', 'clases-conversacion-online', 0.5, 1, 1),
(GETDATE(), GETDATE(), 0, 'PE', 'curso-universitario a1-b2', 0.5, 1, 1),
(GETDATE(), GETDATE(), 0, 'PE', 'clases-conversacion-online', 0.5, 1, 1);
---
DROP TABLE IF EXISTS ProductInterestCountryModifiers
create table ProductInterestCountryModifiers
(
    Id               int identity
        constraint PK_ProductInterestCountryModifiers
            primary key,
    CreationDate     datetime2 not null,
    ModificationDate datetime2 not null,
    IsDeleted        bit       not null,
    CountryCode      nvarchar(max),
    Value            real      not null,
    Around           real      not null,
    IsActive         bit       not null,
    [Order]          int       not null
)
go

INSERT INTO dbo.ProductInterestCountryModifiers  VALUES 
(GETDATE(), GETDATE(), 0, 'ES', 0, 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'AR', 0.16, 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'CO', 0.12, 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'MX', 0, 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'PE', 0, 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'BO', 0.12, 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'BR', 0.12, 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'CR', 0.12, 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'CU', 0.12, 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'EC', 0.15, 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'US', 0.05, 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'GT', 0.15, 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'GQ', 0.15, 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'HN', 0.15, 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'NI', 0.15, 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'PA', 0.15, 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'PY', 0.15, 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'PT', 0.15, 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'PR', 0.15, 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'DO', 0.15, 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'SV', 0.15, 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'UY', 0.15, 0, 1, 1),
(GETDATE(), GETDATE(), 0, 'VE', 0.15, 0, 1, 1);

---
