--INSERT TABLA 1- ProductAmounts
INSERT INTO ProductAmounts VALUES
(GETDATE(),GETDATE(),0,'grado',1450, 1,1),
(GETDATE(),GETDATE(),0,'master-universitario',3900, 1,1),
(GETDATE(),GETDATE(),0,'master',3900, 1,1),
(GETDATE(),GETDATE(),0,'experto',1750, 1,1),
(GETDATE(),GETDATE(),0,'curso',80, 1,1),
(GETDATE(),GETDATE(),0,'oposiciones',790, 1,1),
(GETDATE(),GETDATE(),0,'Clases en directo',940, 1,1),
(GETDATE(),GETDATE(),0,'A1- A2-B1-B2',390, 1,1),
(GETDATE(),GETDATE(),0,'C1-C2',490, 1,1),
(GETDATE(),GETDATE(),0,'Examen Oficial',210, 1,1),
(GETDATE(),GETDATE(),0,'Evaluación Oficial',210, 1,1),
(GETDATE(),GETDATE(),0,'CFC',99, 1,1),
(GETDATE(),GETDATE(),0,'pdd',95, 1,1);

--INSERT TABLA 2- ProductCountryModifiers
INSERT INTO ProductCountryModifiers values
(GETDATE(),GETDATE(),0,'ES', 'grado',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'ES', 'master-universitario',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'ES', 'master',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'ES', 'experto-universitario',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'ES', 'curso-universitario',1,1, 1) ,
(GETDATE(),GETDATE(),0,'ES', 'ope-enfermeria',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'ES', 'clase-conversacion-idiomas',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'ES', 'curso-universitario a1-b2',0.8, 1, 1) ,
(GETDATE(),GETDATE(),0,'ES', 'curso-universitario c1-c2',0.8, 1, 1) ,
(GETDATE(),GETDATE(),0,'ES', 'examen-oficial-idiomas',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'ES', 'evaluacion-oficial-idiomas',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'ES', 'cfc',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'ES', 'programa-desarrollo-directivo',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'AR', 'licenciatura',1, 1, 1),
(GETDATE(),GETDATE(),0,'AR', 'maestria-oficial',0.56, 1, 1) ,
(GETDATE(),GETDATE(),0,'AR', 'maestria',0.56, 1, 1) ,
(GETDATE(),GETDATE(),0,'AR', 'especializacion',0.56, 1, 1) ,
(GETDATE(),GETDATE(),0,'AR', 'diplomado',1.23, 1, 1) ,
(GETDATE(),GETDATE(),0,'AR', 'ope-enfermeria',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'AR', 'clase-conversacion-idiomas',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'AR', 'curso a1-b2',0.9, 1, 1) ,
(GETDATE(),GETDATE(),0,'AR', 'curso c1-c2',0.6, 1, 1) ,
(GETDATE(),GETDATE(),0,'AR', 'examen-oficial-idiomas',0.6, 1, 1) ,
(GETDATE(),GETDATE(),0,'AR', 'evaluacion-oficial-idiomas',0.8, 1, 1) ,
(GETDATE(),GETDATE(),0,'AR', 'cfc',0.8, 1, 1) ,
(GETDATE(),GETDATE(),0,'AR', 'programa-desarrollo-directivo',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'MX', 'licenciatura',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'MX', 'maestria-rvoe',1.17, 1, 1) ,
(GETDATE(),GETDATE(),0,'MX', 'maestria',0.8, 1, 1) ,
(GETDATE(),GETDATE(),0,'MX', 'especializacion',0.8, 1, 1) ,
(GETDATE(),GETDATE(),0,'MX', 'diplomado',0.7, 1, 1) ,
(GETDATE(),GETDATE(),0,'MX', 'ope-enfermeria',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'MX', 'clase-conversacion-idiomas',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'MX', 'curso a1-b2',0.9, 1, 1) ,
(GETDATE(),GETDATE(),0,'MX', 'curso c1-c2',0.6, 1, 1) ,
(GETDATE(),GETDATE(),0,'MX', 'examen-oficial-idiomas',0.6, 1, 1) ,
(GETDATE(),GETDATE(),0,'MX', 'evaluacion-oficial-idiomas',0.8, 1, 1) ,
(GETDATE(),GETDATE(),0,'MX', 'cfc',0.8, 1, 1) ,
(GETDATE(),GETDATE(),0,'MX', 'programa-desarrollo-directivo',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'PE', 'licenciatura',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'PE', 'maestria-oficial',1.03, 1, 1) ,
(GETDATE(),GETDATE(),0,'PE', 'maestria',1.03, 1, 1) ,
(GETDATE(),GETDATE(),0,'PE', 'especializacion',0.97, 1, 1) ,
(GETDATE(),GETDATE(),0,'PE', 'diplomado',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'PE', 'ope-enfermeria',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'PE', 'clase-conversacion-idiomas',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'PE', 'curso a1-b2',0.9, 1, 1) ,
(GETDATE(),GETDATE(),0,'PE', 'curso c1-c2',0.6, 1, 1) ,
(GETDATE(),GETDATE(),0,'PE', 'examen-oficial-idiomas',0.6, 1, 1) ,
(GETDATE(),GETDATE(),0,'PE', 'evaluacion-oficial-idiomas',0.8, 1, 1) ,
(GETDATE(),GETDATE(),0,'PE', 'cfc',0.8, 1, 1),
(GETDATE(),GETDATE(),0,'PE', 'programa-desarrollo-directivo',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'CO', 'licenciatura',0.9, 1, 1),
(GETDATE(),GETDATE(),0,'CO', 'maestria-oficial',0.8, 1, 1) ,
(GETDATE(),GETDATE(),0,'CO', 'maestria',0.8, 1, 1) ,
(GETDATE(),GETDATE(),0,'CO', 'especializacion',0.8, 1, 1) ,
(GETDATE(),GETDATE(),0,'CO', 'diplomado',0.6, 1, 1) ,
(GETDATE(),GETDATE(),0,'CO', 'ope-enfermeria',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'CO', 'clase-conversacion-idiomas',0.9, 1, 1) ,
(GETDATE(),GETDATE(),0,'CO', 'curso a1-b2',0.9, 1, 1) ,
(GETDATE(),GETDATE(),0,'CO', 'curso c1-c2',0.6, 1, 1) ,
(GETDATE(),GETDATE(),0,'CO', 'examen-oficial-idiomas',0.6, 1, 1) ,
(GETDATE(),GETDATE(),0,'CO', 'evaluacion-oficial-idiomas',0.8, 1, 1) ,
(GETDATE(),GETDATE(),0,'CO', 'cfc',0.8, 1, 1),
(GETDATE(),GETDATE(),0,'CO', 'programa-desarrollo-directivo',1, 1, 1) ;
INSERT INTO ProductCountryModifiers values
(GETDATE(),GETDATE(),0,'BO', 'licenciatura',0.8, 1, 1),
(GETDATE(),GETDATE(),0,'BO', 'maestria-oficial',0.56, 1, 1) ,
(GETDATE(),GETDATE(),0,'BO', 'maestria',0.56, 1, 1) ,
(GETDATE(),GETDATE(),0,'BO', 'especializacion',0.56, 1, 1) ,
(GETDATE(),GETDATE(),0,'BO', 'diplomado',0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'BO', 'ope-enfermeria',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'BO', 'clase-conversacion-idiomas',0.8, 1, 1) ,
(GETDATE(),GETDATE(),0,'BO', 'curso a1-b2',0.9, 1, 1) ,
(GETDATE(),GETDATE(),0,'BO', 'curso c1-c2',0.6, 1, 1) ,
(GETDATE(),GETDATE(),0,'BO', 'examen-oficial-idiomas',0.6, 1, 1) ,
(GETDATE(),GETDATE(),0,'BO', 'evaluacion-oficial-idiomas',0.8, 1, 1) ,
(GETDATE(),GETDATE(),0,'BO', 'cfc',0.8, 1, 1),
(GETDATE(),GETDATE(),0,'BO', 'programa-desarrollo-directivo',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'BR', 'licenciatura',0.8, 1, 1),
(GETDATE(),GETDATE(),0,'BR', 'maestria-oficial',0.56, 1, 1) ,
(GETDATE(),GETDATE(),0,'BR', 'maestria',0.56, 1, 1) ,
(GETDATE(),GETDATE(),0,'BR', 'especializacion',0.56, 1, 1) ,
(GETDATE(),GETDATE(),0,'BR', 'diplomado',0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'BR', 'ope-enfermeria',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'BR', 'clase-conversacion-idiomas',0.8, 1, 1) ,
(GETDATE(),GETDATE(),0,'BR', 'curso a1-b2',0.9, 1, 1) ,
(GETDATE(),GETDATE(),0,'BR', 'curso c1-c2',0.6, 1, 1) ,
(GETDATE(),GETDATE(),0,'BR', 'examen-oficial-idiomas',0.6, 1, 1) ,
(GETDATE(),GETDATE(),0,'BR', 'evaluacion-oficial-idiomas',0.8, 1, 1) ,
(GETDATE(),GETDATE(),0,'BR', 'cfc',0.8, 1, 1),
(GETDATE(),GETDATE(),0,'BR', 'programa-desarrollo-directivo',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'CR', 'licenciatura',0.8, 1, 1),
(GETDATE(),GETDATE(),0,'CR', 'maestria-oficial',0.56, 1, 1) ,
(GETDATE(),GETDATE(),0,'CR', 'maestria',0.56, 1, 1) ,
(GETDATE(),GETDATE(),0,'CR', 'especializacion',0.56, 1, 1) ,
(GETDATE(),GETDATE(),0,'CR', 'diplomado',0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'CR', 'ope-enfermeria',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'CR', 'clase-conversacion-idiomas',0.8, 1, 1) ,
(GETDATE(),GETDATE(),0,'CR', 'curso a1-b2',0.9, 1, 1) ,
(GETDATE(),GETDATE(),0,'CR', 'curso c1-c2',0.6, 1, 1) ,
(GETDATE(),GETDATE(),0,'CR', 'examen-oficial-idiomas',0.6, 1, 1) ,
(GETDATE(),GETDATE(),0,'CR', 'evaluacion-oficial-idiomas',0.8, 1, 1) ,
(GETDATE(),GETDATE(),0,'CR', 'cfc',0.8, 1, 1),
(GETDATE(),GETDATE(),0,'CR', 'programa-desarrollo-directivo',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'CU', 'licenciatura',0.8, 1, 1),
(GETDATE(),GETDATE(),0,'CU', 'maestria-oficial',0.56, 1, 1) ,
(GETDATE(),GETDATE(),0,'CU', 'maestria',0.56, 1, 1) ,
(GETDATE(),GETDATE(),0,'CU', 'especializacion',0.56, 1, 1) ,
(GETDATE(),GETDATE(),0,'CU', 'diplomado',0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'CU', 'ope-enfermeria',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'CU', 'clase-conversacion-idiomas',0.8, 1, 1) ,
(GETDATE(),GETDATE(),0,'CU', 'curso a1-b2',0.9, 1, 1) ,
(GETDATE(),GETDATE(),0,'CU', 'curso c1-c2',0.6, 1, 1) ,
(GETDATE(),GETDATE(),0,'CU', 'examen-oficial-idiomas',0.6, 1, 1) ,
(GETDATE(),GETDATE(),0,'CU', 'evaluacion-oficial-idiomas',0.8, 1, 1) ,
(GETDATE(),GETDATE(),0,'CU', 'cfc',0.8, 1, 1),
(GETDATE(),GETDATE(),0,'CU', 'programa-desarrollo-directivo',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'EC', 'licenciatura',0.8, 1, 1),
(GETDATE(),GETDATE(),0,'EC', 'maestria-oficial',0.56, 1, 1) ,
(GETDATE(),GETDATE(),0,'EC', 'maestria',0.56, 1, 1) ,
(GETDATE(),GETDATE(),0,'EC', 'especializacion',0.56, 1, 1) ,
(GETDATE(),GETDATE(),0,'EC', 'diplomado',0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'EC', 'ope-enfermeria',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'EC', 'clase-conversacion-idiomas',0.8, 1, 1) ,
(GETDATE(),GETDATE(),0,'EC', 'curso a1-b2',0.9, 1, 1) ,
(GETDATE(),GETDATE(),0,'EC', 'curso c1-c2',0.6, 1, 1) ,
(GETDATE(),GETDATE(),0,'EC', 'examen-oficial-idiomas',0.6, 1, 1) ,
(GETDATE(),GETDATE(),0,'EC', 'evaluacion-oficial-idiomas',0.8, 1, 1) ,
(GETDATE(),GETDATE(),0,'EC', 'cfc',0.8, 1, 1),
(GETDATE(),GETDATE(),0,'EC', 'programa-desarrollo-directivo',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'US', 'licenciatura',0.8, 1, 1),
(GETDATE(),GETDATE(),0,'US', 'maestria-oficial',0.7, 1, 1) , 
(GETDATE(),GETDATE(),0,'US', 'maestria',0.7, 1, 1) ,
(GETDATE(),GETDATE(),0,'US', 'especializacion',0.7, 1, 1) ,
(GETDATE(),GETDATE(),0,'US', 'diplomado',0.7, 1, 1) ,
(GETDATE(),GETDATE(),0,'US', 'ope-enfermeria',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'US', 'clase-conversacion-idiomas',0.8, 1, 1) ,
(GETDATE(),GETDATE(),0,'US', 'curso a1-b2',0.9, 1, 1) ,
(GETDATE(),GETDATE(),0,'US', 'curso c1-c2',0.6, 1, 1) ,
(GETDATE(),GETDATE(),0,'US', 'examen-oficial-idiomas',0.6, 1, 1) ,
(GETDATE(),GETDATE(),0,'US', 'evaluacion-oficial-idiomas',0.8, 1, 1) ,
(GETDATE(),GETDATE(),0,'US', 'cfc',0.8, 1, 1),
(GETDATE(),GETDATE(),0,'US', 'programa-desarrollo-directivo',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'GT', 'licenciatura',0.8, 1, 1),
(GETDATE(),GETDATE(),0,'GT', 'maestria-oficial',0.56, 1, 1) ,
(GETDATE(),GETDATE(),0,'GT', 'maestria',0.56, 1, 1) ,
(GETDATE(),GETDATE(),0,'GT', 'especializacion',0.56, 1, 1) ,
(GETDATE(),GETDATE(),0,'GT', 'diplomado',0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'GT', 'ope-enfermeria',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'GT', 'clase-conversacion-idiomas',0.8, 1, 1) ,
(GETDATE(),GETDATE(),0,'GT', 'curso a1-b2',0.9, 1, 1) ,
(GETDATE(),GETDATE(),0,'GT', 'curso c1-c2',0.6, 1, 1) ,
(GETDATE(),GETDATE(),0,'GT', 'examen-oficial-idiomas',0.6, 1, 1) ,
(GETDATE(),GETDATE(),0,'GT', 'evaluacion-oficial-idiomas',0.8, 1, 1) ,
(GETDATE(),GETDATE(),0,'GT', 'cfc',0.8, 1, 1),
(GETDATE(),GETDATE(),0,'GT', 'programa-desarrollo-directivo',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'GQ', 'licenciatura',0.8, 1, 1),
(GETDATE(),GETDATE(),0,'GQ', 'maestria-oficial',0.56, 1, 1) ,
(GETDATE(),GETDATE(),0,'GQ', 'maestria',0.56, 1, 1) ,
(GETDATE(),GETDATE(),0,'GQ', 'especializacion',0.56, 1, 1) ,
(GETDATE(),GETDATE(),0,'GQ', 'diplomado',0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'GQ', 'ope-enfermeria',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'GQ', 'clase-conversacion-idiomas',0.8, 1, 1) ,
(GETDATE(),GETDATE(),0,'GQ', 'curso a1-b2',0.9, 1, 1) ,
(GETDATE(),GETDATE(),0,'GQ', 'curso c1-c2',0.6, 1, 1) ,
(GETDATE(),GETDATE(),0,'GQ', 'examen-oficial-idiomas',0.6, 1, 1) ,
(GETDATE(),GETDATE(),0,'GQ', 'evaluacion-oficial-idiomas',0.8, 1, 1) ,
(GETDATE(),GETDATE(),0,'GQ', 'cfc',0.8, 1, 1),
(GETDATE(),GETDATE(),0,'GQ', 'programa-desarrollo-directivo',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'HN', 'licenciatura',0.8, 1, 1),
(GETDATE(),GETDATE(),0,'HN', 'maestria-oficial',0.56, 1, 1) ,
(GETDATE(),GETDATE(),0,'HN', 'maestria',0.56, 1, 1) ,
(GETDATE(),GETDATE(),0,'HN', 'especializacion',0.56, 1, 1) ,
(GETDATE(),GETDATE(),0,'HN', 'diplomado',0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'HN', 'ope-enfermeria',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'HN', 'clase-conversacion-idiomas',0.8, 1, 1) ,
(GETDATE(),GETDATE(),0,'HN', 'curso a1-b2',0.9, 1, 1) ,
(GETDATE(),GETDATE(),0,'HN', 'curso c1-c2',0.6, 1, 1) ,
(GETDATE(),GETDATE(),0,'HN', 'examen-oficial-idiomas',0.6, 1, 1) ,
(GETDATE(),GETDATE(),0,'HN', 'evaluacion-oficial-idiomas',0.8, 1, 1) ,
(GETDATE(),GETDATE(),0,'HN', 'cfc',0.8, 1, 1),
(GETDATE(),GETDATE(),0,'HN', 'programa-desarrollo-directivo',1, 1, 1),
(GETDATE(),GETDATE(),0,'NI', 'licenciatura',0.8, 1, 1),
(GETDATE(),GETDATE(),0,'NI', 'maestria-oficial',0.56, 1, 1) ,
(GETDATE(),GETDATE(),0,'NI', 'maestria',0.56, 1, 1) ,
(GETDATE(),GETDATE(),0,'NI', 'especializacion',0.56, 1, 1) ,
(GETDATE(),GETDATE(),0,'NI', 'diplomado',0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'NI', 'ope-enfermeria',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'NI', 'clase-conversacion-idiomas',0.8, 1, 1) ,
(GETDATE(),GETDATE(),0,'NI', 'curso a1-b2',0.9, 1, 1) ,
(GETDATE(),GETDATE(),0,'NI', 'curso c1-c2',0.6, 1, 1) ,
(GETDATE(),GETDATE(),0,'NI', 'examen-oficial-idiomas',0.6, 1, 1) ,
(GETDATE(),GETDATE(),0,'NI', 'evaluacion-oficial-idiomas',0.8, 1, 1) ,
(GETDATE(),GETDATE(),0,'NI', 'cfc',0.8, 1, 1),
(GETDATE(),GETDATE(),0,'NI', 'programa-desarrollo-directivo',1, 1, 1),
(GETDATE(),GETDATE(),0,'PA', 'licenciatura',0.8, 1, 1),
(GETDATE(),GETDATE(),0,'PA', 'maestria-oficial',0.56, 1, 1) ,
(GETDATE(),GETDATE(),0,'PA', 'maestria',0.56, 1, 1) ,
(GETDATE(),GETDATE(),0,'PA', 'especializacion',0.56, 1, 1) ,
(GETDATE(),GETDATE(),0,'PA', 'diplomado',0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'PA', 'ope-enfermeria',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'PA', 'clase-conversacion-idiomas',0.8, 1, 1) ,
(GETDATE(),GETDATE(),0,'PA', 'curso a1-b2',0.9, 1, 1) ,
(GETDATE(),GETDATE(),0,'PA', 'curso c1-c2',0.6, 1, 1) ,
(GETDATE(),GETDATE(),0,'PA', 'examen-oficial-idiomas',0.6, 1, 1) ,
(GETDATE(),GETDATE(),0,'PA', 'evaluacion-oficial-idiomas',0.8, 1, 1) ,
(GETDATE(),GETDATE(),0,'PA', 'cfc',0.8, 1, 1),
(GETDATE(),GETDATE(),0,'PA', 'programa-desarrollo-directivo',1, 1, 1),
(GETDATE(),GETDATE(),0,'PY', 'licenciatura',0.8, 1, 1),
(GETDATE(),GETDATE(),0,'PY', 'maestria-oficial',0.56, 1, 1) ,
(GETDATE(),GETDATE(),0,'PY', 'maestria',0.56, 1, 1) ,
(GETDATE(),GETDATE(),0,'PY', 'especializacion',0.56, 1, 1) ,
(GETDATE(),GETDATE(),0,'PY', 'diplomado',0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'PY', 'ope-enfermeria',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'PY', 'clase-conversacion-idiomas',0.8, 1, 1) ,
(GETDATE(),GETDATE(),0,'PY', 'curso a1-b2',0.9, 1, 1) ,
(GETDATE(),GETDATE(),0,'PY', 'curso c1-c2',0.6, 1, 1) ,
(GETDATE(),GETDATE(),0,'PY', 'examen-oficial-idiomas',0.6, 1, 1) ,
(GETDATE(),GETDATE(),0,'PY', 'evaluacion-oficial-idiomas',0.8, 1, 1) ,
(GETDATE(),GETDATE(),0,'PY', 'cfc',0.8, 1, 1),
(GETDATE(),GETDATE(),0,'PY', 'programa-desarrollo-directivo',1, 1, 1),
(GETDATE(),GETDATE(),0,'PT', 'licenciatura',0.8, 1, 1),
(GETDATE(),GETDATE(),0,'PT', 'maestria-oficial',0.56, 1, 1) ,
(GETDATE(),GETDATE(),0,'PT', 'maestria',0.56, 1, 1) ,
(GETDATE(),GETDATE(),0,'PT', 'especializacion',0.56, 1, 1) ,
(GETDATE(),GETDATE(),0,'PT', 'diplomado',0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'PT', 'ope-enfermeria',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'PT', 'clase-conversacion-idiomas',0.8, 1, 1) ,
(GETDATE(),GETDATE(),0,'PT', 'curso a1-b2',0.9, 1, 1) ,
(GETDATE(),GETDATE(),0,'PT', 'curso c1-c2',0.6, 1, 1) ,
(GETDATE(),GETDATE(),0,'PT', 'examen-oficial-idiomas',0.6, 1, 1) ,
(GETDATE(),GETDATE(),0,'PT', 'evaluacion-oficial-idiomas',0.8, 1, 1) ,
(GETDATE(),GETDATE(),0,'PT', 'cfc',0.8, 1, 1),
(GETDATE(),GETDATE(),0,'PT', 'programa-desarrollo-directivo',1, 1, 1),
(GETDATE(),GETDATE(),0,'PR', 'licenciatura',0.8, 1, 1),
(GETDATE(),GETDATE(),0,'PR', 'maestria-oficial',0.56, 1, 1) ,
(GETDATE(),GETDATE(),0,'PR', 'maestria',0.56, 1, 1) ,
(GETDATE(),GETDATE(),0,'PR', 'especializacion',0.56, 1, 1) ,
(GETDATE(),GETDATE(),0,'PR', 'diplomado',0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'PR', 'ope-enfermeria',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'PR', 'clase-conversacion-idiomas',0.8, 1, 1) ,
(GETDATE(),GETDATE(),0,'PR', 'curso a1-b2',0.9, 1, 1) ,
(GETDATE(),GETDATE(),0,'PR', 'curso c1-c2',0.6, 1, 1) ,
(GETDATE(),GETDATE(),0,'PR', 'examen-oficial-idiomas',0.6, 1, 1) ,
(GETDATE(),GETDATE(),0,'PR', 'evaluacion-oficial-idiomas',0.8, 1, 1) ,
(GETDATE(),GETDATE(),0,'PR', 'cfc',0.8, 1, 1),
(GETDATE(),GETDATE(),0,'PR', 'programa-desarrollo-directivo',1, 1, 1),
(GETDATE(),GETDATE(),0,'DO', 'licenciatura',0.8, 1, 1),
(GETDATE(),GETDATE(),0,'DO', 'maestria-oficial',0.56, 1, 1) ,
(GETDATE(),GETDATE(),0,'DO', 'maestria',0.56, 1, 1) ,
(GETDATE(),GETDATE(),0,'DO', 'especializacion',0.56, 1, 1) ,
(GETDATE(),GETDATE(),0,'DO', 'diplomado',0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'DO', 'ope-enfermeria',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'DO', 'clase-conversacion-idiomas',0.8, 1, 1) ,
(GETDATE(),GETDATE(),0,'DO', 'curso a1-b2',0.9, 1, 1) ,
(GETDATE(),GETDATE(),0,'DO', 'curso c1-c2',0.6, 1, 1) ,
(GETDATE(),GETDATE(),0,'DO', 'examen-oficial-idiomas',0.6, 1, 1) ,
(GETDATE(),GETDATE(),0,'DO', 'evaluacion-oficial-idiomas',0.8, 1, 1) ,
(GETDATE(),GETDATE(),0,'DO', 'cfc',0.8, 1, 1),
(GETDATE(),GETDATE(),0,'DO', 'programa-desarrollo-directivo',1, 1, 1),
(GETDATE(),GETDATE(),0,'SV', 'licenciatura',0.8, 1, 1),
(GETDATE(),GETDATE(),0,'SV', 'maestria-oficial',0.56, 1, 1) ,
(GETDATE(),GETDATE(),0,'SV', 'maestria',0.56, 1, 1) ,
(GETDATE(),GETDATE(),0,'SV', 'especializacion',0.56, 1, 1) ,
(GETDATE(),GETDATE(),0,'SV', 'diplomado',0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'SV', 'ope-enfermeria',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'SV', 'clase-conversacion-idiomas',0.8, 1, 1) ,
(GETDATE(),GETDATE(),0,'SV', 'curso a1-b2',0.9, 1, 1) ,
(GETDATE(),GETDATE(),0,'SV', 'curso c1-c2',0.6, 1, 1) ,
(GETDATE(),GETDATE(),0,'SV', 'examen-oficial-idiomas',0.6, 1, 1) ,
(GETDATE(),GETDATE(),0,'SV', 'evaluacion-oficial-idiomas',0.8, 1, 1) ,
(GETDATE(),GETDATE(),0,'SV', 'cfc',0.8, 1, 1),
(GETDATE(),GETDATE(),0,'SV', 'programa-desarrollo-directivo',1, 1, 1),
(GETDATE(),GETDATE(),0,'UY', 'licenciatura',0.8, 1, 1),
(GETDATE(),GETDATE(),0,'UY', 'maestria-oficial',0.56, 1, 1) ,
(GETDATE(),GETDATE(),0,'UY', 'maestria',0.56, 1, 1) ,
(GETDATE(),GETDATE(),0,'UY', 'especializacion',0.56, 1, 1) ,
(GETDATE(),GETDATE(),0,'UY', 'diplomado',0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'UY', 'ope-enfermeria',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'UY', 'clase-conversacion-idiomas',0.8, 1, 1) ,
(GETDATE(),GETDATE(),0,'UY', 'curso a1-b2',0.9, 1, 1) ,
(GETDATE(),GETDATE(),0,'UY', 'curso c1-c2',0.6, 1, 1) ,
(GETDATE(),GETDATE(),0,'UY', 'examen-oficial-idiomas',0.6, 1, 1) ,
(GETDATE(),GETDATE(),0,'UY', 'evaluacion-oficial-idiomas',0.8, 1, 1) ,
(GETDATE(),GETDATE(),0,'UY', 'cfc',0.8, 1, 1),
(GETDATE(),GETDATE(),0,'UY', 'programa-desarrollo-directivo',1, 1, 1),
(GETDATE(),GETDATE(),0,'VE', 'licenciatura',0.8, 1, 1),
(GETDATE(),GETDATE(),0,'VE', 'maestria-oficial',0.56, 1, 1) ,
(GETDATE(),GETDATE(),0,'VE', 'maestria',0.56, 1, 1) ,
(GETDATE(),GETDATE(),0,'VE', 'especializacion',0.56, 1, 1) ,
(GETDATE(),GETDATE(),0,'VE', 'diplomado',0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'VE', 'ope-enfermeria',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'VE', 'clase-conversacion-idiomas',0.8, 1, 1) ,
(GETDATE(),GETDATE(),0,'VE', 'curso a1-b2',0.9, 1, 1) ,
(GETDATE(),GETDATE(),0,'VE', 'curso c1-c2',0.6, 1, 1) ,
(GETDATE(),GETDATE(),0,'VE', 'examen-oficial-idiomas',0.6, 1, 1) ,
(GETDATE(),GETDATE(),0,'VE', 'evaluacion-oficial-idiomas',0.8, 1, 1) ,
(GETDATE(),GETDATE(),0,'VE', 'cfc',0.8, 1, 1)
(GETDATE(),GETDATE(),0,'VN', 'programa-desarrollo-directivo',1, 1, 1);

--INSERT TABLA 3- ProductFacultyStudyModifiers"
INSERT INTO ProductFacultyStudyModifiers VALUES
(GETDATE(),GETDATE(),0,'escuela-de-negocios', 'grado',1,1, 1) ,
(GETDATE(),GETDATE(),0,'escuela-de-negocios', 'master-universitario',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'escuela-de-negocios', 'master',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'escuela-de-negocios', 'experto',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'escuela-de-negocios', 'curso',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'escuela-de-negocios', 'oposiciones',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'escuela-de-negocios', 'Clases en directo',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'escuela-de-negocios', 'A1-A2-B1-B2',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'escuela-de-negocios', 'C1-C2',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'escuela-de-negocios', 'Examen Oficial',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'escuela-de-negocios', 'Evaluación Oficial',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'escuela-de-negocios', 'CFC',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'escuela-de-negocios', 'pdd', 1, 1, 1) ,
(GETDATE(),GETDATE(),0,'medicina', 'grado',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'medicina', 'master-universitario',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'medicina', 'master',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'medicina', 'experto',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'medicina', 'curso',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'medicina', 'oposiciones',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'medicina', 'Clases en directo',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'medicina', 'A1-A2-B1-B2',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'medicina', 'C1-C2',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'medicina', 'Examen Oficial',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'medicina', 'Evaluación Oficial',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'medicina', 'CFC',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'medicina', 'pdd', 1, 1, 1) ,
(GETDATE(),GETDATE(),0,'odontologia', 'grado',1.25, 1, 1) ,
(GETDATE(),GETDATE(),0,'odontologia', 'master-universitario',1.25, 1, 1) ,
(GETDATE(),GETDATE(),0,'odontologia', 'master',1.25, 1, 1) ,
(GETDATE(),GETDATE(),0,'odontologia', 'experto',1.25, 1, 1) ,
(GETDATE(),GETDATE(),0,'odontologia', 'curso',1.25, 1, 1) ,
(GETDATE(),GETDATE(),0,'odontologia', 'oposiciones',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'odontologia', 'Clases en directo',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'odontologia', 'A1-A2-B1-B2',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'odontologia', 'C1-C2',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'odontologia', 'Examen Oficial',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'odontologia', 'Evaluación Oficial',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'odontologia', 'CFC',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'odontologia', 'pdd', 1, 1, 1) ,
 (GETDATE(),GETDATE(),0,'farmacia', 'grado',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'farmacia', 'master-universitario',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'farmacia', 'master',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'farmacia', 'experto',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'farmacia', 'curso',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'farmacia', 'oposiciones',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'farmacia', 'Clases en directo',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'farmacia', 'A1-A2-B1-B2',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'farmacia', 'C1-C2',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'farmacia', 'Examen Oficial',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'farmacia', 'Evaluación Oficial',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'farmacia', 'CFC',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'farmacia', 'pdd', 1, 1, 1) ,
 (GETDATE(),GETDATE(),0,'enfermeria', 'grado',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'enfermeria', 'master-universitario',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'enfermeria', 'master',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'enfermeria', 'experto',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'enfermeria', 'curso',0.8, 1, 1) ,
(GETDATE(),GETDATE(),0,'enfermeria', 'oposiciones',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'enfermeria', 'Clases en directo',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'enfermeria', 'A1-A2-B1-B2',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'enfermeria', 'C1-C2',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'enfermeria', 'Examen Oficial',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'enfermeria', 'Evaluación Oficial',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'enfermeria', 'CFC',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'enfermeria', 'pdd', 1, 1, 1) ,
(GETDATE(),GETDATE(),0,'fisioterapia', 'grado',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'fisioterapia', 'master-universitario',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'fisioterapia', 'master',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'fisioterapia', 'experto',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'fisioterapia', 'curso',0.7, 1, 1) ,
(GETDATE(),GETDATE(),0,'fisioterapia', 'oposiciones',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'fisioterapia', 'Clases en directo',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'fisioterapia', 'A1-A2-B1-B2',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'fisioterapia', 'C1-C2',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'fisioterapia', 'Examen Oficial',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'fisioterapia', 'Evaluación Oficial',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'fisioterapia', 'CFC',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'fisioterapia', 'pdd', 1, 1, 1) ,
 (GETDATE(),GETDATE(),0,'nutricion', 'grado',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'nutricion', 'master-universitario',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'nutricion', 'master',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'nutricion', 'experto',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'nutricion', 'curso',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'nutricion', 'oposiciones',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'nutricion', 'Clases en directo',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'nutricion', 'A1-A2-B1-B2',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'nutricion', 'C1-C2',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'nutricion', 'Examen Oficial',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'nutricion', 'Evaluación Oficial',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'nutricion', 'CFC',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'nutricion', 'pdd', 1, 1, 1) ,
(GETDATE(),GETDATE(),0,'psicologia', 'grado',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'psicologia', 'master-universitario',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'psicologia', 'master',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'psicologia', 'experto',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'psicologia', 'curso',0.7, 1, 1) ,
(GETDATE(),GETDATE(),0,'psicologia', 'oposiciones',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'psicologia', 'Clases en directo',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'psicologia', 'A1-A2-B1-B2',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'psicologia', 'C1-C2',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'psicologia', 'Examen Oficial',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'psicologia', 'Evaluación Oficial',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'psicologia', 'CFC',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'psicologia', 'pdd', 1, 1, 1) ,
(GETDATE(),GETDATE(),0,'educacion', 'grado',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'educacion', 'master-universitario',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'educacion', 'master',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'educacion', 'experto',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'educacion', 'curso',0.6, 1, 1) ,
(GETDATE(),GETDATE(),0,'educacion', 'oposiciones',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'educacion', 'Clases en directo',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'educacion', 'A1-A2-B1-B2',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'educacion', 'C1-C2',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'educacion', 'Examen Oficial',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'educacion', 'Evaluación Oficial',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'educacion', 'CFC',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'educacion', 'pdd', 1, 1, 1) ,
(GETDATE(),GETDATE(),0,'filosofia', 'grado',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'filosofia', 'master-universitario',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'filosofia', 'master',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'filosofia', 'experto',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'filosofia', 'curso',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'filosofia', 'oposiciones',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'filosofia', 'Clases en directo',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'filosofia', 'A1-A2-B1-B2',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'filosofia', 'C1-C2',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'filosofia', 'Examen Oficial',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'filosofia', 'Evaluación Oficial',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'filosofia', 'CFC',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'filosofia', 'pdd', 1, 1, 1) ,
(GETDATE(),GETDATE(),0,'escuela-de-idiomas', 'grado',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'escuela-de-idiomas', 'master-universitario',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'escuela-de-idiomas', 'master',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'escuela-de-idiomas', 'experto',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'escuela-de-idiomas', 'curso',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'escuela-de-idiomas', 'oposiciones',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'escuela-de-idiomas', 'Clases en directo',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'escuela-de-idiomas', 'A1-A2-B1-B2',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'escuela-de-idiomas', 'C1-C2',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'escuela-de-idiomas', 'Examen Oficial',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'escuela-de-idiomas', 'Evaluación Oficial',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'escuela-de-idiomas', 'CFC',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'escuela-de-idiomas', 'pdd', 1, 1, 1) ;

--INSERT TABLA 4- ProductCountryFacultyModifiers
INSERT INTO ProductCountryFacultyModifiers VALUES 
(GETDATE(),GETDATE(),0,'ES', 'escuela-de-negocios',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'ES', 'medicina',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'ES', 'odontologia',1.25, 1, 1) ,
(GETDATE(),GETDATE(),0,'ES', 'farmacia',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'ES', 'enfermeria',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'ES', 'fisioterapia',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'ES', 'nutricion',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'ES', 'psicologia',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'ES', 'educacion',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'ES', 'filosofia',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'ES', 'escuela-de-idiomas',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'AR', 'escuela-de-negocios',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'AR', 'medicina',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'AR', 'odontologia',1.25, 1, 1) ,
(GETDATE(),GETDATE(),0,'AR', 'farmacia',0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'AR', 'enfermeria',0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'AR', 'fisioterapia',0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'AR', 'nutricion',0.6, 1, 1) ,
(GETDATE(),GETDATE(),0,'AR', 'psicologia',0.6, 1, 1) ,
(GETDATE(),GETDATE(),0,'AR', 'educacion',0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'AR', 'filosofia',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'AR', 'escuela-de-idiomas',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'CO', 'escuela-de-negocios',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'CO', 'medicina',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'CO', 'odontologia',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'CO', 'farmacia',0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'CO', 'enfermeria',0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'CO', 'fisioterapia',0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'CO', 'nutricion',0.6, 1, 1) ,
(GETDATE(),GETDATE(),0,'CO', 'psicologia',0.6, 1, 1) ,
(GETDATE(),GETDATE(),0,'CO', 'educacion',0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'CO', 'filosofia',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'CO', 'escuela-de-idiomas',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'MX', 'escuela-de-negocios',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'MX', 'medicina',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'MX', 'odontologia',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'MX', 'farmacia',0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'MX', 'enfermeria',0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'MX', 'fisioterapia',0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'MX', 'nutricion',0.6, 1, 1) ,
(GETDATE(),GETDATE(),0,'MX', 'psicologia',0.6, 1, 1) ,
(GETDATE(),GETDATE(),0,'MX', 'educacion',0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'MX', 'filosofia',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'MX', 'escuela-de-idiomas',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'PE', 'escuela-de-negocios',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'PE', 'medicina',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'PE', 'odontologia',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'PE', 'farmacia',0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'PE', 'enfermeria',0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'PE', 'fisioterapia',0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'PE', 'nutricion',0.6, 1, 1) ,
(GETDATE(),GETDATE(),0,'PE', 'psicologia',0.6, 1, 1) ,
(GETDATE(),GETDATE(),0,'PE', 'educacion',0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'PE', 'filosofia',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'PE', 'escuela-de-idiomas',1, 1, 1) ;
INSERT INTO ProductCountryFacultyModifiers VALUES 
(GETDATE(),GETDATE(),0,'BO', 'escuela-de-negocios',0.7, 1, 1) ,
(GETDATE(),GETDATE(),0,'BO', 'medicina',0.8, 1, 1) ,
(GETDATE(),GETDATE(),0,'BO', 'odontologia',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'BO', 'farmacia',0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'BO', 'enfermeria',0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'BO', 'fisioterapia',0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'BO', 'nutricion',0.6, 1, 1) ,
(GETDATE(),GETDATE(),0,'BO', 'psicologia',0.6, 1, 1) ,
(GETDATE(),GETDATE(),0,'BO', 'educacion',0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'BO', 'filosofia',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'BO', 'escuela-de-idiomas',0.7, 1, 1) ,
(GETDATE(),GETDATE(),0,'BR', 'escuela-de-negocios',0.7, 1, 1) ,
(GETDATE(),GETDATE(),0,'BR', 'medicina',0.8, 1, 1) ,
(GETDATE(),GETDATE(),0,'BR', 'odontologia',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'BR', 'farmacia',0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'BR', 'enfermeria',0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'BR', 'fisioterapia',0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'BR', 'nutricion',0.6, 1, 1) ,
(GETDATE(),GETDATE(),0,'BR', 'psicologia',0.6, 1, 1) ,
(GETDATE(),GETDATE(),0,'BR', 'educacion',0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'BR', 'filosofia',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'BR', 'escuela-de-idiomas',0.7, 1, 1) ,
---


-- TABLA 5- ProductCouponDiscountCountryModifiers
INSERT INTO ProductCouponDiscountCountryModifiers VALUES
(GETDATE(),GETDATE(),0,'ES', 'grado',0.862, 1, 1) ,
(GETDATE(),GETDATE(),0,'ES', 'master-universitario',0.7564, 1, 1) ,
(GETDATE(),GETDATE(),0,'ES', 'master',0.7564, 1, 1) ,
(GETDATE(),GETDATE(),0,'ES', 'experto-universitario',0.7142, 1, 1) ,
(GETDATE(),GETDATE(),0,'ES', 'curso-universitario',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'ES', 'ope-enfermeria',0.81, 1, 1) ,
(GETDATE(),GETDATE(),0,'ES', 'clase-conversacion-idiomas',0.8936, 1, 1) ,
(GETDATE(),GETDATE(),0,'ES', 'curso-universitario a1-b2',0.7435, 1, 1) ,
(GETDATE(),GETDATE(),0,'ES', 'curso-universitario c1-c2',0.7959, 1, 1) ,
(GETDATE(),GETDATE(),0,'ES', 'examen-oficial-idiomas',0.5238, 1, 1) ,
(GETDATE(),GETDATE(),0,'ES', 'evaluacion-oficial-idiomas',0.5238, 1, 1) ,
(GETDATE(),GETDATE(),0,'ES', 'cfc',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'ES', 'programa-desarrollo-directivo',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'AR', 'licenciatura',0.862, 1, 1) ,
(GETDATE(),GETDATE(),0,'AR', 'maestria-oficial',0.7104, 1, 1) ,
(GETDATE(),GETDATE(),0,'AR', 'maestria',0.7104, 1, 1) ,
(GETDATE(),GETDATE(),0,'AR', 'especializacion',0.7143, 1, 1) ,
(GETDATE(),GETDATE(),0,'AR', 'diplomado',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'AR', 'ope-enfermeria',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'AR', 'clase-conversacion-idiomas',0.862, 1, 1) ,
(GETDATE(),GETDATE(),0,'AR', 'curso a1-b2',0.8936, 1, 1) ,
(GETDATE(),GETDATE(),0,'AR', 'curso c1-c2',0.7435, 1, 1) ,
(GETDATE(),GETDATE(),0,'AR', 'examen-oficial-idiomas',0.7959, 1, 1) ,
(GETDATE(),GETDATE(),0,'AR', 'evaluacion-oficial-idiomas',0.5238, 1, 1) ,
(GETDATE(),GETDATE(),0,'AR', 'cfc',0.5238, 1, 1) ,
(GETDATE(),GETDATE(),0,'AR', 'programa-desarrollo-directivo',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'CO', 'licenciatura',0.8643, 1, 1) ,
(GETDATE(),GETDATE(),0,'CO', 'maestria-oficial',0.7368, 1, 1) ,
(GETDATE(),GETDATE(),0,'CO', 'maestria',0.7368, 1, 1) ,
(GETDATE(),GETDATE(),0,'CO', 'especializacion',0.5833, 1, 1) ,
(GETDATE(),GETDATE(),0,'CO', 'diplomado',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'CO', 'ope-enfermeria',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'CO', 'clase-conversacion-idiomas',0.8906, 1, 1) ,
(GETDATE(),GETDATE(),0,'CO', 'curso a1-b2',0.7404, 1, 1) ,
(GETDATE(),GETDATE(),0,'CO', 'curso c1-c2',0.7941, 1, 1) ,
(GETDATE(),GETDATE(),0,'CO', 'examen-oficial-idiomas',0.7941, 1, 1) ,
(GETDATE(),GETDATE(),0,'CO', 'evaluacion-oficial-idiomas',0.4927, 1, 1) ,
(GETDATE(),GETDATE(),0,'CO', 'cfc',0.4927, 1, 1) ,
(GETDATE(),GETDATE(),0,'CO', 'programa-desarrollo-directivo',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'MX', 'licenciatura',0.8621, 1, 1) ,
(GETDATE(),GETDATE(),0,'MX', 'maestria-rvoe',0.7, 1, 1) ,
(GETDATE(),GETDATE(),0,'MX', 'maestria',0.7, 1, 1) ,
(GETDATE(),GETDATE(),0,'MX', 'especializacion',0.7, 1, 1) ,
(GETDATE(),GETDATE(),0,'MX', 'diplomado',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'MX', 'ope-enfermeria',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'MX', 'clase-conversacion-idiomas',0.8621, 1, 1) ,
(GETDATE(),GETDATE(),0,'MX', 'curso a1-b2',0.8999, 1, 1) ,
(GETDATE(),GETDATE(),0,'MX', 'curso c1-c2',0.7775, 1, 1) ,
(GETDATE(),GETDATE(),0,'MX', 'examen-oficial-idiomas',0.823, 1, 1) ,
(GETDATE(),GETDATE(),0,'MX', 'evaluacion-oficial-idiomas',0.9109, 1, 1) ,
(GETDATE(),GETDATE(),0,'MX', 'cfc',0.9109, 1, 1) ,
(GETDATE(),GETDATE(),0,'MX', 'programa-desarrollo-directivo',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'PE', 'licenciatura',0.8637, 1, 1) ,
(GETDATE(),GETDATE(),0,'PE', 'maestria-oficial',0.9, 1, 1) ,
(GETDATE(),GETDATE(),0,'PE', 'maestria',0.9, 1, 1) ,
(GETDATE(),GETDATE(),0,'PE', 'especializacion',0.8986, 1, 1) ,
(GETDATE(),GETDATE(),0,'PE', 'diplomado',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'PE', 'ope-enfermeria',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'PE', 'clase-conversacion-idiomas',0.8637, 1, 1) ,
(GETDATE(),GETDATE(),0,'PE', 'curso a1-b2',0.8892, 1, 1) ,
(GETDATE(),GETDATE(),0,'PE', 'curso c1-c2',0.7466, 1, 1) ,
(GETDATE(),GETDATE(),0,'PE', 'examen-oficial-idiomas',0.7989, 1, 1) ,
(GETDATE(),GETDATE(),0,'PE', 'evaluacion-oficial-idiomas',0.4933, 1, 1) ,
(GETDATE(),GETDATE(),0,'PE', 'cfc',0.4933, 1, 1),
(GETDATE(),GETDATE(),0,'PE', 'programa-desarrollo-directivo',1, 1, 1) ;

---TABLA 6 - ProductCouponDiscountFacultyStudyModifiers
INSERT INTO ProductCouponDiscountFacultyStudyModifiers VALUES
(GETDATE(),GETDATE(),0,'escuela-de-negocios', 'grado',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'escuela-de-negocios', 'master-universitario',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'escuela-de-negocios', 'master',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'escuela-de-negocios', 'experto',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'escuela-de-negocios', 'curso',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'escuela-de-negocios', 'oposiciones',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'escuela-de-negocios', 'Clases en directo',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'escuela-de-negocios', 'A1-A2-B1-B2',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'escuela-de-negocios', 'C1-C2',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'escuela-de-negocios', 'Examen Oficial',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'escuela-de-negocios', 'Evaluación Oficial',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'escuela-de-negocios', 'CFC',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'escuela-de-negocios', 'pdd', 1, 1, 1) ,
(GETDATE(),GETDATE(),0,'medicina', 'grado',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'medicina', 'master-universitario',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'medicina', 'master',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'medicina', 'experto',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'medicina', 'curso',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'medicina', 'oposiciones',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'medicina', 'Clases en directo',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'medicina', 'A1-A2-B1-B2',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'medicina', 'C1-C2',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'medicina', 'Examen Oficial',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'medicina', 'Evaluación Oficial',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'medicina', 'CFC',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'medicina', 'pdd', 1, 1, 1) ,
(GETDATE(),GETDATE(),0,'odontologia', 'grado',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'odontologia', 'master-universitario',1.0657, 1, 1) ,
(GETDATE(),GETDATE(),0,'odontologia', 'master',1.0657, 1, 1) ,
(GETDATE(),GETDATE(),0,'odontologia', 'experto',1.1455, 1, 1) ,
(GETDATE(),GETDATE(),0,'odontologia', 'curso',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'odontologia', 'oposiciones',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'odontologia', 'Clases en directo',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'odontologia', 'A1-A2-B1-B2',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'odontologia', 'C1-C2',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'odontologia', 'Examen Oficial',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'odontologia', 'Evaluación Oficial',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'odontologia', 'CFC',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'odontologia', 'pdd', 1, 1, 1) ,
(GETDATE(),GETDATE(),0,'farmacia', 'grado',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'farmacia', 'master-universitario',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'farmacia', 'master',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'farmacia', 'experto',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'farmacia', 'curso',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'farmacia', 'oposiciones',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'farmacia', 'Clases en directo',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'farmacia', 'A1-A2-B1-B2',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'farmacia', 'C1-C2',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'farmacia', 'Examen Oficial',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'farmacia', 'Evaluación Oficial',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'farmacia', 'CFC',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'farmacia', 'pdd', 1, 1, 1) ,
(GETDATE(),GETDATE(),0,'enfermeria', 'grado',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'enfermeria', 'master-universitario',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'enfermeria', 'master',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'enfermeria', 'experto',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'enfermeria', 'curso',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'enfermeria', 'oposiciones',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'enfermeria', 'Clases en directo',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'enfermeria', 'A1-A2-B1-B2',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'enfermeria', 'C1-C2',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'enfermeria', 'Examen Oficial',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'enfermeria', 'Evaluación Oficial',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'enfermeria', 'CFC',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'enfermeria', 'pdd', 1, 1, 1) ,
(GETDATE(),GETDATE(),0,'fisioterapia', 'grado',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'fisioterapia', 'master-universitario',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'fisioterapia', 'master',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'fisioterapia', 'experto',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'fisioterapia', 'curso',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'fisioterapia', 'oposiciones',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'fisioterapia', 'Clases en directo',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'fisioterapia', 'A1-A2-B1-B2',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'fisioterapia', 'C1-C2',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'fisioterapia', 'Examen Oficial',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'fisioterapia', 'Evaluación Oficial',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'fisioterapia', 'CFC',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'fisioterapia', 'pdd', 1, 1, 1) ,
(GETDATE(),GETDATE(),0,'nutricion', 'grado',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'nutricion', 'master-universitario',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'nutricion', 'master',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'nutricion', 'experto',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'nutricion', 'curso',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'nutricion', 'oposiciones',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'nutricion', 'Clases en directo',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'nutricion', 'A1-A2-B1-B2',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'nutricion', 'C1-C2',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'nutricion', 'Examen Oficial',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'nutricion', 'Evaluación Oficial',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'nutricion', 'CFC',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'nutricion', 'pdd', 1, 1, 1) ,
(GETDATE(),GETDATE(),0,'psicologia', 'grado',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'psicologia', 'master-universitario',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'psicologia', 'master',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'psicologia', 'experto',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'psicologia', 'curso',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'psicologia', 'oposiciones',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'psicologia', 'Clases en directo',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'psicologia', 'A1-A2-B1-B2',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'psicologia', 'C1-C2',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'psicologia', 'Examen Oficial',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'psicologia', 'Evaluación Oficial',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'psicologia', 'CFC',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'psicologia', 'pdd', 1, 1, 1) ,
(GETDATE(),GETDATE(),0,'educacion', 'grado',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'educacion', 'master-universitario',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'educacion', 'master',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'educacion', 'experto',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'educacion', 'curso',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'educacion', 'oposiciones',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'educacion', 'Clases en directo',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'educacion', 'A1-A2-B1-B2',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'educacion', 'C1-C2',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'educacion', 'Examen Oficial',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'educacion', 'Evaluación Oficial',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'educacion', 'CFC',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'educacion', 'pdd', 1, 1, 1) ,
(GETDATE(),GETDATE(),0,'filosofia', 'grado',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'filosofia', 'master-universitario',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'filosofia', 'master',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'filosofia', 'experto',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'filosofia', 'curso',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'filosofia', 'oposiciones',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'filosofia', 'Clases en directo',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'filosofia', 'A1-A2-B1-B2',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'filosofia', 'C1-C2',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'filosofia', 'Examen Oficial',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'filosofia', 'Evaluación Oficial',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'filosofia', 'CFC',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'filosofia', 'pdd', 1, 1, 1) ,
(GETDATE(),GETDATE(),0,'escuela-de-idiomas', 'grado',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'escuela-de-idiomas', 'master-universitario',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'escuela-de-idiomas', 'master',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'escuela-de-idiomas', 'experto',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'escuela-de-idiomas', 'curso',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'escuela-de-idiomas', 'oposiciones',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'escuela-de-idiomas', 'Clases en directo',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'escuela-de-idiomas', 'A1-A2-B1-B2',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'escuela-de-idiomas', 'C1-C2',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'escuela-de-idiomas', 'Examen Oficial',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'escuela-de-idiomas', 'Evaluación Oficial',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'escuela-de-idiomas', 'CFC',1, 1, 1) ,
(GETDATE(),GETDATE(),0,'escuela-de-idiomas', 'pdd', 1, 1, 1);

--TABLA 7 - ProductScholarshipCountryModifier
INSERT INTO ProductScholarshipCountryModifiers  Values
(GETDATE(),GETDATE(),0,'ES', 'grado',0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'ES', 'master-universitario',0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'ES', 'master',0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'ES', 'experto-universitario',0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'ES', 'curso-universitario',0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'ES', 'ope-enfermeria',0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'ES', 'clase-conversacion-idiomas',0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'ES', 'curso-universitario a1-b2',0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'ES', 'curso-universitario c1-c2',0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'ES', 'examen-oficial-idiomas',0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'ES', 'evaluacion-oficial-idiomas',0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'ES', 'cfc',0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'ES', 'programa-desarrollo-directivo', 0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'AR', 'licenciatura',0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'AR', 'maestria-oficial',0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'AR', 'maestria',0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'AR', 'especializacion',0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'AR', 'diplomado',0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'AR', 'ope-enfermeria',0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'AR', 'clase-conversacion-idiomas',0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'AR', 'curso a1-b2',0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'AR', 'curso c1-c2',0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'AR', 'examen-oficial-idiomas',0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'AR', 'evaluacion-oficial-idiomas',0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'AR', 'cfc',0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'AR', 'programa-desarrollo-directivo', 0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'CO', 'licenciatura',0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'CO', 'maestria-oficial',0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'CO', 'maestria',0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'CO', 'especializacion',0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'CO', 'diplomado',0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'CO', 'ope-enfermeria',0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'CO', 'clase-conversacion-idiomas',0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'CO', 'curso a1-b2',0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'CO', 'curso c1-c2',0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'CO', 'examen-oficial-idiomas',0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'CO', 'evaluacion-oficial-idiomas',0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'CO', 'cfc',0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'CO', 'programa-desarrollo-directivo', 0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'MX', 'licenciatura',0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'MX', 'maestria-rvoe',0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'MX', 'maestria',0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'MX', 'especializacion',0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'MX', 'diplomado',0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'MX', 'ope-enfermeria',0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'MX', 'clase-conversacion-idiomas',0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'MX', 'curso a1-b2',0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'MX', 'curso c1-c2',0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'MX', 'examen-oficial-idiomas',0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'MX', 'evaluacion-oficial-idiomas',0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'MX', 'cfc',0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'MX', 'programa-desarrollo-directivo', 0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'PE', 'licenciatura',0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'PE', 'maestria-oficial',0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'PE', 'maestria',0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'PE', 'especializacion',0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'PE', 'diplomado',0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'PE', 'ope-enfermeria',0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'PE', 'clase-conversacion-idiomas',0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'PE', 'curso a1-b2',0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'PE', 'curso c1-c2',0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'PE', 'examen-oficial-idiomas',0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'PE', 'evaluacion-oficial-idiomas',0.5, 1, 1) ,
(GETDATE(),GETDATE(),0,'PE', 'cfc',0.5, 1, 1)
(GETDATE(),GETDATE(),0,'PE','programa-desarrollo-directivo', 0.5, 1, 1) ;


--"-- TABLA 9 - ProductInterestCountryModifiers
INSERT INTO ProductInterestCountryModifiers VALUES
(GETDATE(),GETDATE(),0,'ES', 0, 1, 1, 1) ,
(GETDATE(),GETDATE(),0,'AR',0.16, 1, 1, 1) ,
(GETDATE(),GETDATE(),0,'CO', 0.12, 1, 1, 1) ,
(GETDATE(),GETDATE(),0,'MX', 0, 1, 1, 1) ,
(GETDATE(),GETDATE(),0,'PE', 0, 1, 1, 1) ,
(GETDATE(),GETDATE(),0,'BO', 0.12, 1, 1, 1) ,
(GETDATE(),GETDATE(),0,'BR', 0.12, 1, 1, 1) ,
(GETDATE(),GETDATE(),0,'CR', 0.12, 1, 1, 1) ,
(GETDATE(),GETDATE(),0,'CU', 0.12, 1, 1, 1) ,
(GETDATE(),GETDATE(),0,'EC', 0.15, 1, 1, 1) ,
(GETDATE(),GETDATE(),0,'US', 0.05, 1, 1, 1) ,
(GETDATE(),GETDATE(),0,'GT', 0.15, 1, 1, 1) ,
(GETDATE(),GETDATE(),0,'GQ', 0.15, 1, 1, 1) ,
(GETDATE(),GETDATE(),0,'HN', 0.15, 1, 1, 1) ,
(GETDATE(),GETDATE(),0,'NI', 0.15, 1, 1, 1) ,
(GETDATE(),GETDATE(),0,'PA', 0.15, 1, 1, 1) ,
(GETDATE(),GETDATE(),0,'PY', 0.15, 1, 1, 1) ,
(GETDATE(),GETDATE(),0,'PT', 0.15, 1, 1, 1) ,
(GETDATE(),GETDATE(),0,'PR', 0.15, 1, 1, 1) ,
(GETDATE(),GETDATE(),0,'DO', 0.15, 1, 1, 1) ,
(GETDATE(),GETDATE(),0,'SV', 0.15, 1, 1, 1) ,
(GETDATE(),GETDATE(),0,'UY', 0.15, 1, 1, 1) ,
(GETDATE(),GETDATE(),0,'VE', 0.15, 1, 1, 1) ;
